import json
from pathlib import Path
R=Path(__file__).resolve().parents[1];m=json.loads((R/'public/models/seen-alhambra-2024.json').read_text())
lines=['# Seen Health — final-document model audit','',f"Source: {m['source']['title']} · {m['source']['author']} · January 10, 2024 · 91 pages.",'','## Scope and result','','The entire PDF was rendered, its text extracted, and all pages visually inventoried. Named elevations and sections were inspected at enlarged resolution. This is a source audit and reconstruction, not a completed as-built certification. All readable source statements are preserved in the page register. Rooms and construction elements that cannot be verified from the compressed presentation remain explicitly unresolved.','','The earlier 2023 approximate viewer is superseded by a meters-based model using the final 2024 layout. Street and parking context uses the architect’s actual overhead rendering. The basement, upper mezzanine, future second-floor office shell, and roof have been added. No unavailable basement or future-office partition layout has been invented.','','## Scale','','One scene unit equals one meter. The visible clinic rectangle on page 12 is calibrated to the 3,254 sq ft clinic program area on page 14. This produces %.8f source pixels per meter. That calibration assumes the stated program area corresponds to the traced clinic perimeter; the document does not resolve net/gross boundary conventions. It is not a surveyed length calibration, and no dimensional tolerance is claimed.'%m['calibration']['pixelsPerMeter'],'','## Explicit dimensions','', '| Meaning | Source | Model | Pages |','|---|---|---|---|']
for d in m['dimensions']:lines.append(f"| {d['meaning']} | {d['sourceValue']} | {d['value']} m | {', '.join(map(str,d['pages']))} |")
lines+=['','The 12 ft datum is a wall-treatment dimension, not a ceiling or floor-to-floor height. The roof crown, upper-floor elevations and basement depth remain inferred.','','## Published program areas','','| Program | Area, sq ft | Page |','|---|---:|---:|']
for p in m['programs']:lines.append(f"| {p['name']} | {p['publishedSqFt']:,} | {p['sourcePage']} |")
lines+=['','Ground-floor schedule total: **17,318 sq ft**. Do not add a published combined program area again for each component zone. Do not equate a gross traced polygon with a published net program area.','','## Outstanding accuracy inputs','']
for i in m['accuracyIssues']:lines += [f"### {i['title']}",i['detail'],f"Source pages: {', '.join(map(str,i['pages']))}.",'']
lines+=['## Room-by-room register','','Stable trace IDs are used where architectural room numbers are unavailable. Numeric labels are only asserted when the source explicitly names them. Furniture positions are traced or interpreted from source imagery; asset dimensions are inferred until the installed furniture schedule is supplied.','','| Trace ID | Room / space | Level | Source pages | Review status |','|---|---|---|---|---|']
for r in m['rooms']:lines.append(f"| {r['id']} | {r['name']} | {r['levelId']} | {', '.join(map(str,r['referencePages']))} | {r['status']} |")
lines+=['','## Page-by-page findings','']
for p in m['referencePages']:lines += [f"### Page {p['page']} — {p['title']}",f"Evidence type: {p['evidenceType']}. Review: {p['reviewStatus']}.",p['findings'],'']
lines+=['## Element-level inventory','','Every wall segment has an ID, endpoints in meters, inferred thickness/height and source pages. Every furniture/equipment instance has an ID, reusable asset reference, position, rotation, scale, room association where identifiable, and status. Facade pieces and landscape battens are also stored as separate data elements. These are auditable reconstruction elements; their presence does not mean every real construction line or hidden item is documented.','','## Reuse and interchange','','The current model is `public/models/seen-alhambra-2024.json`, schema 2.0, SI units. No site coordinates belong in the generic renderer. Change facility data to replace a building, change an asset definition to replace all uses, or edit one object transform to change a specific placement. Source imagery travels separately at its declared paths. GLB exports are in meters and assemble the full building independent of the current exploded/cutaway view.','','## Validation limits','','Checks cover schema/JSON round trips, reference links, known area arithmetic, triangulation, nonzero wall geometry, model assembly, visibility/level transformations and portable object geometry. Browser visual and interaction testing has not been performed. The PDF does not support claiming pixel-perfect as-built accuracy yet.']
(R/'public/models/accuracy-register.md').write_text('\n'.join(lines))
(R/'MODEL_NOTES.md').write_text('\n'.join(lines[:next(i for i,v in enumerate(lines) if v=='## Outstanding accuracy inputs')])+'\n\nFull page and room audit: public/models/accuracy-register.md.\nPortable format guide: public/models/facility-format.md.\n')
print('Wrote full source audit and model notes.')
